[build]
  functions = "netlify/functions"
  publish = "dist"  # or "build" depending on your build output directory

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true